### ISSUE TITLE
Migrate to homebrew/core

### ISSUE THREAD

**Issue by zmwangx** [jarun/homebrew-nnn#1]
`nnn` has been accepted into homebrew/core. This tap can be deprecated now. There are three ways forward:

1. Leave this tap alone. `brew install jarun/nnn/nnn` still works, but it will be stuck at whatever version that is in this tap.

2. Delete this tap. `brew install jarun/nnn/nnn` will no longer work, `brew update` or `brew upgrade` will throw an error.

3. Keep this tap, remove `nnn.rb` and add a `tap_migrations.json`:

   ```json
   {"nnn": "homebrew/core"}
   ```

   This way, `brew install jarun/nnn/nnn` still works and is automatically redirected to homebrew/core; people who previously installed `jarun/nnn/nnn` will be upgraded in the future without manual intervention.

I prefer 3.

**Comment by zmwangx** [comment]
Oh, and the instruction in jarun/nnn's readme should be updated to

```
brew install nnn
```

**Comment by jarun** [comment]
If we go by 2, will removing nnn and installing it using `brew install nnn` work?

**Comment by zmwangx** [comment]
Yes.

**Comment by jarun** [comment]
So:

```
brew uninstall nnn
brew install nnn
```

right?

**Comment by zmwangx** [comment]
Yes.

**Comment by zmwangx** [comment]
Oh and `brew untap jarun/nnn`.

**Comment by jarun** [comment]
This branch is so gone.... ;)

**Comment by jarun** [comment]
or,

`brew untap jarun/nnn/nnn`?

**Comment by zmwangx** [comment]
`jarun/nnn` is the tap. `jarun/nnn/nnn` is the qualified formula name. So it is `jarun/nnn` that needs to be untapped. (`brew install jarun/nnn/nnn` performs an automatic `brew tap jarun/nnn`.)

**Comment by jarun** [comment]
Check https://github.com/jarun/nnn/issues/13 where I documented the procedure.

**Comment by zmwangx** [comment]
LGTM.
